Title: "Allison's Portfolio"
show downloads: true
theme: jekyll-theme-minimal
author:
  # Biographic information
  avatar           : /image_123650291 (1).JPG
  name             : Allison Kim
  Github           : https://github.com/allison02kim
  Linkedin         : https://.\linkedin.com/in/allisonykim
  Tableau          : https://public.tableau.com/app/profile/allison.kim5958/vizzes
  # Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
